# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00f2da6f8a80bbec89174249bfa9d03c02b21799f91714eceee7e628629680ebe9939e8daa6abe4d936ea16175c5bf7ffdfba07a95fad407ae7ad3e4262c1494

test:
  secret_key_base: 0aa5bdaca1e3b5cd3a9cd869c5832164a5051762f5947d12fbde7eae6802364818aca6b60f481973b78f5caa59c491434cef51cb570129b7d733351bdaea1bf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
